### ISSUE TITLE
when add react-router and redux to this multi-entry-react, it render blank page

### ISSUE THREAD

**Issue by hahazexia** [iamandrewluca/example-cra-multi-entry#3]
when i don't add anything in this example, it work fine.
but when i add react-router and redux to it, then `npm run start`, there are 2 problems:

1.the index.html and login.html both render nothing, they are all blank page
2. sass file is not inject into the final html, so there is no style in page

i can't find the reason, maybe my router and redux code is wrong?but i try the same way in single page application, they are working fine.

do you have some ideas about this?

by the way, i use 
create-react-app 3.4.1 
"react-redux": "^7.2.0",
"react-router": "^5.1.2",
"react-router-dom": "^5.1.2",
"redux": "^4.0.5",

**Comment by iamandrewluca** [comment]
This is just an experimental CRA eject, you need to configure react-router for this to work

**Comment by hahazexia** [comment]
https://github.com/hahazexia/cra-electron
